"""
Django settings for dhaka_web project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
import os
import sys
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local development environment variables from the project root.
load_dotenv(BASE_DIR / '.env')

logger = logging.getLogger(__name__)
RUNNING_TESTS = 'test' in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


def _env_bool(name: str, default: bool = False) -> bool:
    """Read a boolean environment variable."""
    value = os.getenv(name)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    return default


def _env_list(name: str, default=None) -> list[str]:
    """Read comma-separated environment values."""
    value = os.getenv(name)
    if not value:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


APP_ENV = (os.getenv("APP_ENV") or "development").strip().lower()
RAILWAY_ENVIRONMENT = (os.getenv("RAILWAY_ENVIRONMENT") or "").strip().lower()
RAILWAY_PUBLIC_DOMAIN = (os.getenv("RAILWAY_PUBLIC_DOMAIN") or "").strip()
IS_PRODUCTION = bool(
    APP_ENV in {"production", "prod"}
    or RAILWAY_ENVIRONMENT in {"production", "prod"}
    or RAILWAY_PUBLIC_DOMAIN
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-*k-l=czgoag7g@z_b^_8z#i9k*zbsre67gw&f(!9!4*m$phroj",
)
if IS_PRODUCTION and SECRET_KEY.startswith("django-insecure-"):
    raise ImproperlyConfigured("Set SECRET_KEY in Railway before deploying.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", default=not IS_PRODUCTION)

default_allowed_hosts = ["*"] if not IS_PRODUCTION else []
if RAILWAY_PUBLIC_DOMAIN:
    default_allowed_hosts.append(RAILWAY_PUBLIC_DOMAIN)

# Get ALLOWED_HOSTS from env, but filter out literal Railway variable references
allowed_hosts_raw = _env_list("ALLOWED_HOSTS", default=default_allowed_hosts)
ALLOWED_HOSTS = [
    h for h in allowed_hosts_raw
    if h and not h.startswith("${{") and not h.endswith("}}")
]

# If no valid hosts after filtering, use defaults
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = default_allowed_hosts


CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")
if RAILWAY_PUBLIC_DOMAIN:
    railway_origin = f"https://{RAILWAY_PUBLIC_DOMAIN}"
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'complaints',  # Our app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dhaka_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dhaka_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def _is_placeholder(value: str) -> bool:
    """Return True when an env value is empty or still uses example placeholders."""
    text = (value or "").strip()
    if not text:
        return True

    placeholders = (
        "your-db-password",
        "REPLACE_WITH_SUPABASE_DB_PASSWORD",
        "db.your-project.supabase.co",
    )
    return any(placeholder in text for placeholder in placeholders)


def _postgres_database_from_url():
    """Build Django database settings from a Supabase Postgres URL."""
    database_url = ""
    for env_name in (
        "SUPABASE_DATABASE_URL",
        "DATABASE_URL",
    ):
        database_url = (os.getenv(env_name) or "").strip()
        if not _is_placeholder(database_url):
            break

    if _is_placeholder(database_url):
        return None

    parsed = urlparse(database_url)
    if parsed.scheme not in {"postgres", "postgresql"} or not parsed.hostname:
        return None

    query = parse_qs(parsed.query)
    sslmode = (
        (query.get("sslmode") or [None])[-1]
        or (os.getenv("DB_SSLMODE") or "").strip()
        or "require"
    )

    config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(parsed.path.lstrip("/") or os.getenv("DB_NAME", "postgres")),
        "USER": unquote(parsed.username or os.getenv("DB_USER", "postgres")),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname,
        "PORT": str(parsed.port or os.getenv("DB_PORT", "5432")),
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "600")),
    }
    if sslmode:
        config["OPTIONS"] = {"sslmode": sslmode}
    return config


def _postgres_database_from_parts():
    """Build Django database settings from separate Supabase Postgres env vars."""
    host = (os.getenv("DB_HOST") or "").strip()
    password = (os.getenv("DB_PASSWORD") or "").strip()

    if _is_placeholder(host) or _is_placeholder(password):
        return None

    config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "postgres"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": password,
        "HOST": host,
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "600")),
    }

    sslmode = (os.getenv("DB_SSLMODE") or "").strip() or "require"
    if sslmode:
        config["OPTIONS"] = {"sslmode": sslmode}
    return config


def _sqlite_database():
    """Fallback SQLite settings for local-only development."""
    sqlite_path = os.getenv("SQLITE_PATH", str(BASE_DIR / "db.sqlite3"))
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": sqlite_path,
    }


POSTGRES_DATABASE = _postgres_database_from_url() or _postgres_database_from_parts()
if POSTGRES_DATABASE:
    DATABASES = {"default": POSTGRES_DATABASE}
elif not _env_bool("ALLOW_SQLITE_FALLBACK", default=False):
    raise ImproperlyConfigured(
        "Supabase Postgres is required, but no usable database settings were found. "
        "Set SUPABASE_DATABASE_URL, DATABASE_URL, or DB_HOST/DB_PASSWORD."
    )
else:
    logger.warning(
        "Supabase Postgres credentials are incomplete or still placeholders. "
        "Using SQLite only because ALLOW_SQLITE_FALLBACK=true."
    )
    DATABASES = {"default": _sqlite_database()}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('LOCAL_STORAGE_PATH', BASE_DIR / 'storage'))
DOCUMENT_OUTPUT_DIR = Path(os.getenv('DOCUMENT_OUTPUT_DIR', str(MEDIA_ROOT / 'generated_docs')))
POLICY_DIRECTORY = Path(os.getenv('POLICY_DIRECTORY', BASE_DIR / '_archive'))
ENABLE_SUPABASE_STORAGE = os.getenv('ENABLE_SUPABASE_STORAGE', 'true').lower() == 'true'
SUPABASE_MEDIA_BUCKET = os.getenv('SUPABASE_MEDIA_BUCKET', 'complaint-media')
SUPABASE_DOCUMENT_BUCKET = os.getenv('SUPABASE_DOCUMENT_BUCKET', 'generated-documents')
SUPABASE_STORAGE_SIGNED_URL_TTL = int(os.getenv('SUPABASE_STORAGE_SIGNED_URL_TTL', '3600'))

ENABLE_EMAIL = os.getenv('ENABLE_EMAIL', 'false').lower() == 'true'
ENABLE_TAVILY_SEARCH = os.getenv('ENABLE_TAVILY_SEARCH', 'false').lower() == 'true'
ENABLE_ADVANCED_RAG = os.getenv('ENABLE_ADVANCED_RAG', 'false').lower() == 'true'
SUPABASE_URL = os.getenv('SUPABASE_URL', '')
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY', '')

USE_SUPABASE_STORAGE = bool(
    ENABLE_SUPABASE_STORAGE
    and not RUNNING_TESTS
    and SUPABASE_URL
    and SUPABASE_SERVICE_ROLE_KEY
)

if not USE_SUPABASE_STORAGE:
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
    DOCUMENT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

if USE_SUPABASE_STORAGE:
    STORAGES = {
        'default': {
            'BACKEND': 'complaints.storage_backends.SupabaseStorage',
            'OPTIONS': {
                'bucket_name': SUPABASE_MEDIA_BUCKET,
                'base_path': '',
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
            'OPTIONS': {
                'location': str(MEDIA_ROOT),
                'base_url': MEDIA_URL,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_SMTP_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_SMTP_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD', '')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_SENDER', EMAIL_HOST_USER or 'noreply@example.com')
EMAIL_FROM_NAME = os.getenv('EMAIL_FROM_NAME', 'Dhaka Nagorik Bot')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'complaints': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
