# Generated by Django 6.0.4 on 2026-04-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_chatsession_chatmessage_extractedcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='generated_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_chat_sessions', to='complaints.complaint'),
        ),
    ]
