# Generated by Django 6.0.4 on 2026-04-14 22:04

import complaints.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_chatsession_generated_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='generated_docx_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='complaint',
            name='generated_pdf_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=complaints.models.chat_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.chatmessage')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
