# Generated by Django 6.0.4 on 2026-04-15 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_email_error_complaint_email_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Approval'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('awaiting_citizen_confirmation', 'Awaiting Citizen Confirmation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=40),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='status_change',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('awaiting_citizen_confirmation', 'Awaiting Citizen Confirmation'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='ComplaintActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('filed', 'Filed'), ('acknowledged', 'Acknowledged'), ('resolution_requested', 'Resolution Requested'), ('citizen_confirmed', 'Citizen Confirmed'), ('citizen_reopened', 'Citizen Reopened'), ('note_added', 'Note Added'), ('reminder_sent', 'Reminder Sent')], max_length=40)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='complaints.complaint')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
