create extension if not exists vector with schema extensions;

create table if not exists public.vector_documents (
    id bigint generated by default as identity primary key,
    collection_name text not null,
    document_id text not null,
    document text not null,
    metadata jsonb not null default '{}'::jsonb,
    embedding extensions.vector(384) not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (collection_name, document_id)
);

create index if not exists vector_documents_collection_name_idx
    on public.vector_documents (collection_name);

create index if not exists vector_documents_metadata_idx
    on public.vector_documents
    using gin (metadata);

create index if not exists vector_documents_embedding_idx
    on public.vector_documents
    using hnsw (embedding extensions.vector_cosine_ops);

create or replace function public.set_vector_documents_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists vector_documents_set_updated_at on public.vector_documents;

create trigger vector_documents_set_updated_at
before update on public.vector_documents
for each row
execute function public.set_vector_documents_updated_at();

create or replace function public.match_vector_documents(
    query_embedding extensions.vector(384),
    match_count integer default 5,
    match_collection text default null
)
returns table (
    document_id text,
    document text,
    metadata jsonb,
    similarity double precision
)
language sql
stable
as $$
    select
        vector_documents.document_id,
        vector_documents.document,
        vector_documents.metadata,
        1 - (vector_documents.embedding <=> query_embedding) as similarity
    from public.vector_documents
    where match_collection is null
        or vector_documents.collection_name = match_collection
    order by vector_documents.embedding <=> query_embedding
    limit greatest(match_count, 1);
$$;
